// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6dlBirkGMUyi4GFVBgv8MqKb5sPet0Fk',
    appId: '1:568000509385:web:5d233bdc62096a3fdc6418',
    messagingSenderId: '568000509385',
    projectId: 'power-tracker-gh',
    authDomain: 'power-tracker-gh.firebaseapp.com',
    storageBucket: 'power-tracker-gh.firebasestorage.app',
    measurementId: 'G-V98GZ0DH0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByKB_WgCgW5mJHRruwD_SpA2y7W7A4hAA',
    appId: '1:568000509385:android:77929f138c94e130dc6418',
    messagingSenderId: '568000509385',
    projectId: 'power-tracker-gh',
    storageBucket: 'power-tracker-gh.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJnXwNiBpkeQU-JeBhP7CjVEEZidMUD9k',
    appId: '1:568000509385:ios:a4a5ec2558b4cafedc6418',
    messagingSenderId: '568000509385',
    projectId: 'power-tracker-gh',
    storageBucket: 'power-tracker-gh.firebasestorage.app',
    iosBundleId: 'com.example.powerTrackerGh',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJnXwNiBpkeQU-JeBhP7CjVEEZidMUD9k',
    appId: '1:568000509385:ios:a4a5ec2558b4cafedc6418',
    messagingSenderId: '568000509385',
    projectId: 'power-tracker-gh',
    storageBucket: 'power-tracker-gh.firebasestorage.app',
    iosBundleId: 'com.example.powerTrackerGh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6dlBirkGMUyi4GFVBgv8MqKb5sPet0Fk',
    appId: '1:568000509385:web:dbefc0e7ffd6e7cadc6418',
    messagingSenderId: '568000509385',
    projectId: 'power-tracker-gh',
    authDomain: 'power-tracker-gh.firebaseapp.com',
    storageBucket: 'power-tracker-gh.firebasestorage.app',
    measurementId: 'G-QX85R3M4V8',
  );
}
